### ISSUE TITLE
Python implementation request

### ISSUE THREAD

**Issue by impredicative** [baptistar/BOCS#2]
A Python 3 implementation will prove very useful. MATLAB is accessible to few due to its cost.

**Comment by WillKoehrsen** [comment]
There is an online tool to convert Matlab scripts to Python called [OMPC](http://ompclib.appspot.com/m2py). It's a lot to ask the original authors to go back and redo all of their work in a different language, but a determined individual could probably take this on.

**Comment by baptistar** [comment]
Thank you for the suggestion @impredicative! We will definitely try to put together a Python 3 implementation soon using the tool @WillKoehrsen recommended.

**Comment by baptistar** [comment]
We have completed our Python implementation for BOCS, and It is now available in the BOCSpy folder! Please let us know if you have any questions, and we'll be happy to answer them :).

**Comment by impredicative** [comment]
This is great. It would help for the Python implementation to be in its own GitHub repo that is independent of this one, with the same language-agnostic bells and whistles that accompany this repo, e.g. a readme. This is useful because a user usually wants one or the other, not both. The point is to have the Python code be more production ready like the M code is.
